Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      InstanceType: t2.micro
      KeyName: udacity-debugging
      ImageId: 'ami-0928f4202481dfdf6' # you may need to find out what instance types are available in your region - use https://cloud-images.ubuntu.com/locator/ec2/
      Tags:
        - Key: "project"
          Value: "udacity"
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0